vich_uploader:
    db_driver: orm

    mappings:
       shoes:
           uri_prefix: /images/shoes
           upload_destination: '%kernel.project_dir%/public/images/shoes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
           

           
